# Generated by Django 3.0.4 on 2020-04-30 12:22

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Mobiles',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('brand', models.CharField(max_length=30)),
                ('release_date', models.DateField()),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='shop/images')),
                ('description', models.CharField(max_length=1000)),
                ('design', reviews.models.IntegerRangeField()),
                ('camera', reviews.models.IntegerRangeField()),
                ('battery', reviews.models.IntegerRangeField()),
                ('performance', reviews.models.IntegerRangeField()),
                ('value_for_money', reviews.models.IntegerRangeField()),
            ],
        ),
    ]
