# Generated by Django 3.0.4 on 2020-04-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20200430_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_mobile',
            name='m_slug',
            field=models.CharField(default='mobile=<django.db.models.fields.CharField>+<django.db.models.fields.CharField>', max_length=120),
        ),
    ]
