# Generated by Django 3.0.4 on 2020-04-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_product_mobile_m_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_mobile',
            name='m_slug',
            field=models.CharField(default='mobile=', max_length=120),
        ),
    ]
